name: Publish kit-bundles

on:
  push:
    branches:
      - main
      - beta
      - alpha
    tags:
      - "*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.17.1]

    steps:
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout kit-bundles
        uses: actions/checkout@master

      - name: Semantic Release
        run: |
          npx semantic-release@19.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
